### ISSUE TITLE
windows 호환성 문제

### ISSUE THREAD

**Issue by wolyosung** [shin285/KOMORAN#32]
버전 3.3.3 기준으로 windows에서 작동하지 않는 것으로 보입니다.

Komoran class 초기화를 다음 코드로 실행하면 오류가 납니다.
```java
 Komoran komoran = new Komoran(DEFAULT_MODEL.FULL);
```

오류 메시지는 아래와 같습니다.
```
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at kr.co.shineware.nlp.komoran.modeler.model.PosTable.load(PosTable.java:107)
	at kr.co.shineware.nlp.komoran.core.model.Resources.loadPosTable(Resources.java:87)
	at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:81)
	at KomoranTest.main(KomoranTest.java:10)
java.lang.NullPointerException
	at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode.load(AhoCorasickNode.java:129)
	at kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.load(AhoCorasickDictionary.java:33)
	at kr.co.shineware.nlp.komoran.modeler.model.IrregularTrie.load(IrregularTrie.java:79)
	at kr.co.shineware.nlp.komoran.core.model.Resources.loadIrregular(Resources.java:114)
	at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:82)
	at KomoranTest.main(KomoranTest.java:10)
java.lang.NullPointerException
	at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode.load(AhoCorasickNode.java:129)
	at kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.load(AhoCorasickDictionary.java:33)
	at kr.co.shineware.nlp.komoran.modeler.model.Observation.load(Observation.java:84)
	at kr.co.shineware.nlp.komoran.core.model.Resources.loadObservation(Resources.java:96)
	at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:83)
	at KomoranTest.main(KomoranTest.java:10)
java.lang.NullPointerException
	at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at kr.co.shineware.nlp.komoran.modeler.model.Transition.load(Transition.java:91)
	at kr.co.shineware.nlp.komoran.core.model.Resources.loadTransition(Resources.java:105)
	at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:84)
	at KomoranTest.main(KomoranTest.java:10)
Exception in thread "main" java.lang.NullPointerException
	at kr.co.shineware.nlp.komoran.modeler.model.PosTable.getId(PosTable.java:58)
	at kr.co.shineware.nlp.komoran.core.model.Lattice.makeStartNode(Lattice.java:70)
	at kr.co.shineware.nlp.komoran.core.model.Lattice.init(Lattice.java:64)
	at kr.co.shineware.nlp.komoran.core.model.Lattice.<init>(Lattice.java:55)
	at kr.co.shineware.nlp.komoran.core.Komoran.analyze(Komoran.java:139)
	at KomoranTest.main(KomoranTest.java:13)
```

아마 Komoran class의 다음 부분이 문제인 것 같습니다.
```java
        InputStream posTableFile = this.getResourceStream(modelPath + File.separator + "pos.table");
        InputStream irrModelFile = this.getResourceStream(modelPath + File.separator + "irregular.model");
        InputStream observationFile = this.getResourceStream(modelPath + File.separator + "observation.model");
        InputStream transitionFile = this.getResourceStream(modelPath + File.separator + "transition.model");
```

File.separator가 windows에서 `\`로 처리되어서 발생하는 문제인 것 같습니다.

**Comment by shin285** [comment]
리포팅 감사드립니다! @dolpang2 님께서 contribute 해주셔서 해당 이슈는 종료하겠습니다. 감사합니다 :)
