### ISSUE TITLE
komoran 3.3.4 버전 안드로이드 API 24-5에서 실행했을 때 오류 발생

### ISSUE THREAD

**Issue by bjh1460** [shin285/KOMORAN#72]
## 기능 설명
_어떤 상황에서, 무엇을 추가하거나 / 변경하길 원하시나요?_
현 코모란 버전은 안드로이드 스튜디오 API 24-25(Nougat)에서 실행했을 때 오류가 발생합니다. 

## 추가 정보
_참고할 수 있는 다른 정보가 있다면 남겨주세요._

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.komoran, PID: 4578
    java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;[Ljava/lang/CharSequence;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:79)
        at com.example.komoran.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by shin285** [comment]
해당 이슈는 android 24-25에서 "File.seperator"를 지원하지 않아서 생기는 문제로 보입니다. 상위 API를 사용하시면 문제를 해결하실 수 있습니다. 근본적인 해결을 위해서 "File.seperator"를 대체하는 코드로 수정하겠습니다. 이슈업 감사드립니다 :)

**Comment by shin285** [comment]
해당 이슈는 https://github.com/shin285/KOMORAN/pull/71 merge로 해결되었습니다. 감사합니다.
