### ISSUE TITLE
3.3.8 Release ./gradlew jar 동작시

### ISSUE THREAD

**Issue by waring92** [shin285/KOMORAN#81]
## 문제 설명
3.3.8 Release 판에서 ./gradlew jar 로 수동JAR 파일 생성후 import 하여 구동하면, 아래 에러 발생

```
Exception in thread "main" java.lang.NoClassDefFoundError: kr/co/shineware/ds/aho_corasick/AhoCorasickDictionary
	at kr.co.shineware.nlp.komoran.modeler.model.Observation.init(Observation.java:41)
	at kr.co.shineware.nlp.komoran.modeler.model.Observation.<init>(Observation.java:37)
	at kr.co.shineware.nlp.komoran.core.model.Resources.init(Resources.java:67)
	at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:82)
	at App.main(App.java:10)
Caused by: java.lang.ClassNotFoundException: kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at kr.co.shineware.nlp.komoran.modeler.model.Observation.init(Observation.java:41)
	at kr.co.shineware.nlp.komoran.modeler.model.Observation.<init>(Observation.java:37)
	at kr.co.shineware.nlp.komoran.core.model.Resources.init(Resources.java:67)
	at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:82)
	at App.main(App.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:415)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:192)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)
```

## 재현 경로
./gradlew jar 후 생성된 Jar파일 이용해 App.java 예제 코드 구동

## 기대 상황
_정상적인 상황에서는 어떻게 동작해야 한다고 생각하세요?_

## 환경 정보
* OS 종류 / 버전: MacOS Catalina
* Komoran 버전: 3.3.8
* Java 버전: OpenJDK 12.0.1

**Comment by waring92** [comment]
Shineware Repo.내에서 kr/co/shineware/ds/aho_corasick 코드를 찾아 src에 위치시켰으나,
kr/co/shineware/util 에 대한 에러가 발생하였으며 동일하게 찾아서 위치시켰더니,
모든 형태소 분석 결과가 NA로 나오고 있습니다. 아무래도 모델이 들어있지 않은 것 같습니다.

**Comment by shin285** [comment]
gradle을 사용하고 계시면 jitpack을 이용하여 의존성을 추가하시면 해당 문제를 해결하실 수 있습니다.
사용 방법은 아래 링크를 참조해주세요. 
https://docs.komoran.kr/firststep/installation.html?utm_source=komoran-repo&utm_medium=Referral&utm_campaign=github-demo

더불어 말씀하신 방법과 같이 jar 파일을 생성 후에 사용할 수 있는 use case가 있으니 fatJar 형태로 추출하는 gradle job을 추가하도록 하겠습니다. 

jitpack 사용해보시고 댓글 부탁드립니다 :)

**Comment by waring92** [comment]
답변 감사드립니다. 설치하기에 나온 것 참고하였습니다.
build.gradle 파일에 KOMORAN 3.3.8 추가하여 돌려보았지만(아래), 결과는 동일했습니다.
`implementation 'com.github.shin285:KOMORAN:3.3.8'`

#82 에 따라 fatJAR를 만들어보니 동작은 성공했으나, 결과가 아래처럼 나왔습니다.
```
javac -cp "./libs/KOMORAN.jar:" App.java; java -cp ".:./libs/KOMORAN.jar:" App
대한민국은 민주공화국이다./NA
( 0, 14) 대한민국은 민주공화국이다./NA
```

**Comment by dolpang2** [comment]
@waring92 사용하고자 하는 App에서 Gradle에 implementation을 추가하시면 fatJar를 사용하실 필요는 없습니다. 혹시 가능하다면 작업중인 프로젝트 repository나 코드를 알려주시면 저희가 좀 더 도와드리기 쉬울 것 같습니다

**Comment by waring92** [comment]
@dolpang2 
Docs 내에 [Gradle/Maven 없이 형태소 분석 따라하기](https://docs.komoran.kr/firststep/tutorial-java.html) 를 구동시키고자 합니다. Docs는 3.3.4 기준으로 되어있지만, 3.3.8 의 Jar 파일을 이용하려 했습니다.
이를 위해 3.3.8 Git Clone하여, implementation 추가하고 ./gradlew jar 혹은 ./gradlew uber 를 구동시켰습니다.

`./gradlew jar`를 이용하면 위 질문과 같은 NoClassDefFoundError 에러가 나고, 
`./gradlew uber`를 이용하면 전체 문장이 /NA로 출력됩니다.

**Comment by dolpang2** [comment]
@waring92 uber의 경우 gradle script를 따로 수정하신건가요? 아니면 스크립트 수정없이 단순히 gradlew uber인가요?

**Comment by waring92** [comment]
@dolpang2 
#83의 [Commit](https://github.com/shin285/KOMORAN/pull/83/commits/4bf042358f160fc16695292f70e53d96fcf14f7e) 내용 확인하고 추가하였습니다.

**Comment by dolpang2** [comment]
@waring92 혹시 https://github.com/shineware/RKOMORAN/tree/master/inst/java 의 jar를 받아서 테스트해보시겠어요? fatJar로 만든 파일이며, 제 환경 (Windows 10, Java 8)에서 테스트했을 때 정상 동작 확인했습니다. 만약 위 링크의 jar가 제대로 동작한다면, gradle에서 뭔가 만드실 때 빠진 부분이 있을 것 같네요.
![image](https://user-images.githubusercontent.com/9076745/71667582-1566c100-2da9-11ea-9e7c-7e96b3df267c.png)

**Comment by shin285** [comment]
@waring92 NA로만 나온다면 인코딩 문제인 것 같습니다. build.gradle에 아래 두 줄과 같은 인코딩 설정이 되어있을까요?
`compileJava.options.encoding = "UTF-8"`
`compileTestJava.options.encoding = "UTF-8"`

**Comment by waring92** [comment]
문제 해결했습니다. ./gradlew uber로 JAR 파일 생성 후,
Komoran komoran = new Komoran(DEFAULT_MODEL.**LIGHT**);
FULL은 /NA로 동작되고, LIGHT에서는 올바르게 동작하는 것을 확인했습니다.

@dolpang2 
해당 링크의 JAR파일도 FULL MODEL에서는 NA로만 동작합니다.
LIGHT에서는 첨부해주신 이미지와 같이 올바른 결과가 출력됩니다.

@shin285 
인코딩 설정은 build.gradle 내에 이미 들어있었습니다.

**Comment by shin285** [comment]
FULL관련해서 확인해보겠습니다. 이슈리포팅 감사드립니다.
